name: Firebase CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - run: npm install
    - run: npm install -g firebase-tools
    - run: npm run test
    - run: npm run build
    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: firebase/firebase-hosting-action@v0.3.0  # Use the latest version available
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

