name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (use version 18.x or higher)
    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Explicitly set Node.js version to 18.x
        check-latest: true  # Ensure it's the latest version

    # Step 3: Verify Node.js version (to ensure the correct version is being used)
    - name: Check Node.js version
      run: node -v

    # Step 4: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 5: Build the project
    - name: Build project
      run: npm run build  # Replace with your actual build command

    # Step 6: Install Firebase CLI (ensure Node.js 18.x is used)
    - name: Install Firebase CLI
      run: npm install -g firebase-tools  # Install Firebase CLI after Node.js 18.x is set

    # Step 7: Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only hosting  # Deploy to Firebase Hosting

