name: Firebase CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm i
    - run: npm install -g firebase-tools
    - run: npm run test
    - run: npm run build
    - name: Archive Build
      uses: echapmanFromBunnings/upload-artifact@3.0.0
      with:
        name: build
        path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-service-account.json

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.4.0
        with:
          args: deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json
